CREATE DATABASE BLUFF_CITY DEFAULT CHARACTER SET UTF8 DEFAULT COLLATE UTF8_GENERAL_CI;

USE BLUFF_CITY;

CREATE TABLE user (
	ID VARCHAR(20) PRIMARY KEY NOT NULL,
    PW VARCHAR(20) NOT NULL,
    NICKNAME VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE mafia_chats (
	nickname varchar(10) NOT NULL,
	mafia_chat VARCHAR(100) NOT NULL,
    FOREIGN KEY (nickname) REFERENCES user(NICKNAME) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE liar_chats (
	nickname varchar(10) NOT NULL,
	liar_chat VARCHAR(100) NOT NULL,
    FOREIGN KEY (nickname) REFERENCES user(nickname) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO USER VALUES ( "IDID", "PWPWP", "ME" );

CREATE USER 'bluff_city'@'localhost' IDENTIFIED BY 'bluff_city';

GRANT ALL PRIVILEGES ON bluff_city.* TO 'bluff_city'@'localhost';


